version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
  
  tool-runner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    links:
      - redis
    volumes:
      - ./tool_mounts:/app/tool_mounts
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MOUNT_BASE_DIR: /app/tool_mounts
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 5555
      